import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { chromium, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { authenticate, baseUrl } from './auth-fixture.mjs';

await mkdir('.qa/lobby', { recursive: true });
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const report = [];
try {
  for (const [width, height] of [[1280,720], [1440,900], [1920,1080], [768,900], [375,812]]) {
    const context = await browser.newContext({ viewport: { width, height } });
    const peerContext = await browser.newContext({ reducedMotion: 'reduce' });
    const peer = await peerContext.newPage();
    const peerName = `목록친구${width}`;
    await authenticate(peerContext, peerName);
    await peer.goto(baseUrl);
    await peer.locator('.arrival-screen').waitFor({ state: 'hidden' });
    await peer.getByRole('button', { name: '방 만들기', exact: true }).click();
    await expect(peer.locator('.hud-round')).toHaveText('1 / 4명');
    const peerRoomId = (await peer.locator('.hud-room small').innerText()).replace('#', '');
    const page = await context.newPage();
    const peerRow = page.locator('.room-row').filter({ hasText: `#${peerRoomId}` });
    await authenticate(context);
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(baseUrl);
    await page.locator('.arrival-screen').waitFor({ state: 'hidden' });
    await page.locator('.lobby-backdrop[data-ready="true"]').waitFor();
    await page.evaluate(() => document.fonts.ready);
    await page.locator('.profile-character img').evaluate(image => image.decode());
    await page.screenshot({ path: `.qa/lobby/start-${width}.png`, fullPage: true });
    await expect(peerRow).toContainText('1 / 4');
    await expect(page.locator('[data-connection="connected"]')).toBeVisible();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    const violations = (await new AxeBuilder({ page }).analyze()).violations;
    await expect(page.locator('.profile-account-name')).toHaveText('동민');
    await page.getByRole('button', { name: '방 만들기', exact: true }).click();
    await expect(page.getByRole('button', { name: '경매 시작하기' })).toBeDisabled();
    await expect(page.getByRole('button', { name: '준비하기', exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: '방 목록', exact: true }).click();
    await expect(peerRow).toContainText('1 / 4');
    await page.getByLabel('방 이름 검색').fill('없는방');
    await page.getByRole('heading', { name: '찾는 방이 없어요' }).waitFor();
    await page.screenshot({ path: `.qa/lobby/empty-${width}.png`, fullPage: true });
    await page.getByRole('button', { name: '전체 방 보기' }).click();
    await page.getByLabel('입장 가능한 방만').check();
    await expect(peerRow).toBeVisible();
    await expect(peerRow.locator('.room-state')).toHaveText('입장 가능');
    await page.getByLabel('입장 가능한 방만').uncheck();
    await page.locator('.directory-loadout summary').click();
    await page.getByRole('button', { name: '1번 토마토 장착 해제' }).click();
    await page.getByRole('button', { name: /토마토 보유 .*장착/ }).click();
    await page.screenshot({ path: `.qa/lobby/loadout-${width}.png`, fullPage: true });
    await page.locator('.directory-loadout summary').click();
    await page.getByRole('button', { name: '게임 방법', exact: true }).click();
    await page.getByRole('dialog').waitFor();
    await expect(page.getByRole('dialog')).not.toContainText('봇');
    await page.getByRole('dialog').evaluate(element => Promise.all(element.getAnimations({ subtree: true }).map(animation => animation.finished)));
    await page.screenshot({ path: `.qa/lobby/rules-${width}.png` });
    violations.push(...(await new AxeBuilder({ page }).analyze()).violations);
    await page.getByRole('button', { name: '좋아, 이해했어!' }).click();
    await page.getByRole('button', { name: '장난 상점', exact: true }).click();
    await page.getByRole('dialog').waitFor();
    await page.getByRole('dialog').evaluate(element => Promise.all(element.getAnimations({ subtree: true }).map(animation => animation.finished)));
    await page.screenshot({ path: `.qa/lobby/shop-${width}.png` });
    violations.push(...(await new AxeBuilder({ page }).analyze()).violations);
    await page.getByRole('button', { name: '닫기', exact: true }).click();
    await peerRow.getByRole('button', { name: `${peerName}의 경매장 입장`, exact: true }).click();
    await expect(page.getByRole('button', { name: '준비하기', exact: true })).toBeEnabled();
    await expect(page.getByRole('button', { name: '경매 시작하기' })).toHaveCount(0);
    assert.equal(await page.locator('.lobby-shell').count(), 0);
    await page.screenshot({ path: `.qa/lobby/entered-${width}.png` });
    await page.getByRole('button', { name: '방 목록', exact: true }).click();
    await expect(page.locator('.profile-account-name')).toHaveText('동민');
    await page.getByRole('button', { name: '방 만들기' }).click();
    await expect(page.getByRole('button', { name: '경매 시작하기' })).toBeDisabled();
    await expect(page.getByRole('button', { name: '준비하기', exact: true })).toHaveCount(0);
    await page.getByRole('button', { name: '방 목록', exact: true }).click();
    await expect(peerRow).toContainText('1 / 4');
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await peerRow.getByRole('button', { name: `${peerName}의 경매장 입장`, exact: true }).focus();
    await page.keyboard.press('Tab');
    assert.notEqual(await page.locator(':focus').evaluate(element => getComputedStyle(element).outlineStyle), 'none');
    await page.screenshot({ path: `.qa/lobby/focus-${width}.png`, fullPage: true });
    report.push({ width, height, errors, violations: violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => ({ target: n.target, summary: n.failureSummary })) })) });
    console.log('LOBBY', width, JSON.stringify(report.at(-1)));
    assert.deepEqual(errors, []);
    await peer.getByRole('button', { name: '방 목록', exact: true }).click();
    await expect(peerRow).toHaveCount(0);
    await peerContext.close();
    await context.close();
  }
} finally {
  await writeFile('.qa/lobby/report.json', JSON.stringify(report, null, 2));
  await browser.close();
}
assert.ok(report.every(result => result.violations.length === 0));
